//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platformy_projekt
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class memy
    {
        public int id { get; set; }
        public string meme_url { get; set; }
        public Nullable<float> upvotes { get; set; }
        public Nullable<System.DateTime> data_top { get; set; }
        public string uzytkownik { get; set; }
    }
}
